site_name: Reflex Wiki
site_url: https://reflexwiki.gg

theme:
  name: material
  logo: reflexlogo.svg
  favicon: reflexlogo.svg
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: red
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  features:
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/reflex
      name: Reflex Arena on Discord
    - icon: fontawesome/brands/steam
      link: https://store.steampowered.com/app/328070/Reflex_Arena/
      name: Reflex Arena on Steam
    - icon: fontawesome/brands/twitter
      link: https://x.com/ReflexArena
      name: Reflex Arena on Twitter
