site_name: Reflex Arena Wiki
site_url: https://reflexwiki.gg

nav:
  - Reflex Arena:
    - Home: index.md
    - What is Reflex Arena?: reflex-arena/what-is-reflex.md
    - Reflex's Netcode: reflex-arena/netcode.md
  - Gameplay:
    - Gameplay: gameplay/index.md
    - Game Modes: gameplay/game-modes.md
    - Mutators: gameplay/mutators.md
    - Movement: gameplay/movement.md
    - Weapons: gameplay/weapons.md
    - Pickups: gameplay/pickups.md
    - Maps: gameplay/maps.md
    - Rulesets: gameplay/rulesets.md
  - Level Editor:
    - Overview: level-editor/overview.md
    - Getting Started: level-editor/getting-started.md
    - Tutorials: level-editor/tutorials.md
  - Replay Editor:
    - Overview: replay-editor/overview.md
    - Getting Started: replay-editor/getting-started.md
    - Tutorials: replay-editor/tutorials.md
  - HUD Editor / Widgets:
    - Widgets: hud-editor/widgets.md
  - Guides:
    - Guides: guides/index.md
    - Console Commands: guides/console-commands.md
    - Config Files: guides/config-files.md
    - Creating a Dedicated Server: guides/dedicated-server.md

theme:
  name: material
  logo: reflexlogo.svg
  favicon: reflexlogo.svg
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: red
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  features:
    # - navigation.footer
    - navigation.instant
    # - navigation.tabs
    - navigation.tracking
    - navigation.indexes

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/reflex
      name: Reflex Arena on Discord
    - icon: fontawesome/brands/steam
      link: https://store.steampowered.com/app/328070/Reflex_Arena/
      name: Reflex Arena on Steam
    - icon: fontawesome/brands/twitter
      link: https://x.com/ReflexArena
      name: Reflex Arena on Twitter
